### DISCUSSION TITLE
关于中文特化版本train_ms.py训练问题

### DISCUSSION THREAD

**Discussion by windforestfiremountain** [fishaudio/Bert-VITS2#298] [Q&A]
作者您好，在使用最新中文特化版本调用的时候出现了分布式训练报错（硬件环境4090四卡config.yml配置WORLD_SIZE: 1
    ，LOCAL_RANK: 1，RANK: 12），报错日志如下,请问有什么解决方法吗？
```
Using noise scaled MAS for VITS2
Use existed model, skip downloading.
INFO:models:Loaded checkpoint 'Data/models/WD_0.pth' (iteration 0)
ERROR:models:emb_g.weight is not in the checkpoint
INFO:models:Loaded checkpoint 'Data/models/G_0.pth' (iteration 0)
INFO:models:Loaded checkpoint 'Data/models/D_0.pth' (iteration 0)
******************检测到模型存在，epoch为 1，gloabl step为 0*********************
Some weights of the model checkpoint at ./slm/wavlm-base-plus were not used when initializing WavLMModel: ['encoder.pos_conv_embed.conv.weight_v', 'encoder.pos_conv_embed.conv.weight_g']
- This IS expected if you are initializing WavLMModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing WavLMModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of WavLMModel were not initialized from the model checkpoint at ./slm/wavlm-base-plus and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'encoder.pos_conv_embed.conv.parametrizations.weight.original0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                                                                                            | 0/47 [00:08<?, ?it/s]
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f3fa6fa0617 in /data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f3fa6f5b98d in /data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f3fa7051c38 in /data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x126123e (0x7f3fa837d23e in /data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x519806 (0x7f4011c81806 in /data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x55ca7 (0x7f3fa6f85ca7 in /data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0x1e3 (0x7f3fa6f7dcb3 in /data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f3fa6f7de49 in /data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #8: <unknown function> + 0x7ca2c8 (0x7f4011f322c8 in /data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: THPVariable_subclass_dealloc(_object*) + 0x325 (0x7f4011f32675 in /data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x10a7bb (0x55fce92e87bb in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #11: <unknown function> + 0x124d2a (0x55fce9302d2a in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #12: <unknown function> + 0x17a7cf (0x55fce93587cf in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #13: _PyEval_EvalFrameDefault + 0x5de1 (0x55fce92fb6d1 in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #14: _PyFunction_Vectorcall + 0xfe (0x55fce93058be in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #15: _PyEval_EvalFrameDefault + 0x3cf (0x55fce92f5cbf in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #16: _PyFunction_Vectorcall + 0xfe (0x55fce93058be in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #17: _PyEval_EvalFrameDefault + 0x3cf (0x55fce92f5cbf in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #18: _PyEval_EvalCodeWithName + 0x316 (0x55fce92f4906 in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #19: PyEval_EvalCodeEx + 0x39 (0x55fce938e449 in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #20: PyEval_EvalCode + 0x1b (0x55fce938e40b in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #21: <unknown function> + 0x1d1fd6 (0x55fce93affd6 in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #22: <unknown function> + 0x1d0ff2 (0x55fce93aeff2 in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #23: <unknown function> + 0x99e89 (0x55fce9277e89 in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #24: PyRun_SimpleFileExFlags + 0x3b4 (0x55fce92779eb in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #25: <unknown function> + 0x8d473 (0x55fce926b473 in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #26: Py_BytesMain + 0x37 (0x55fce9382267 in /data/anaconda3/envs/BertVITS2/bin/python3.8)
frame #27: __libc_start_main + 0xf3 (0x7f4033d84083 in /lib/x86_64-linux-gnu/libc.so.6)
frame #28: <unknown function> + 0x1a416d (0x55fce938216d in /data/anaconda3/envs/BertVITS2/bin/python3.8)

[2024-01-18 22:51:43,668] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 0 (pid: 981904) of binary: /data/anaconda3/envs/BertVITS2/bin/python3.8
Traceback (most recent call last):
  File "/data/anaconda3/envs/BertVITS2/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/anaconda3/envs/BertVITS2/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
train_ms.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-18_22:51:43
  host      : d8e6cbd31686
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 981904)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 981904
=======================================================
```

**Comment by windforestfiremountain** [comment]
conda list 的环境如下：
```
(BertVITS2) root@d8e6cbd31686:~/project/Bert-VITS2# conda list
# packages in environment at /data/anaconda3/envs/BertVITS2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.9.1                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aliyun-python-sdk-core    2.14.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.2                   pypi_0    pypi
altair                    5.2.0                    pypi_0    pypi
amfm-decompy              1.0.11                   pypi_0    pypi
aniso8601                 9.0.1                    pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.2.0                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
av                        11.0.0                   pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beartype                  0.16.4                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bibtexparser              2.0.0b5                  pypi_0    pypi
bidict                    0.22.1                   pypi_0    pypi
bleach                    6.1.0                    pypi_0    pypi
bzip2                     1.0.8                hd590300_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2023.11.17           hbcca054_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cachetools                5.3.2                    pypi_0    pypi
certifi                   2023.11.17               pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
clldutils                 3.22.1                   pypi_0    pypi
cmudict                   1.0.16                   pypi_0    pypi
cn2an                     0.5.22                   pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
coloredlogs               14.0                     pypi_0    pypi
colorlog                  6.8.0                    pypi_0    pypi
comm                      0.2.1                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              41.0.7                   pypi_0    pypi
csvw                      3.2.2                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cython                    0.29.37                  pypi_0    pypi
dacite                    1.8.1                    pypi_0    pypi
datasets                  2.13.0                   pypi_0    pypi
debugpy                   1.8.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecated                1.2.14                   pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
distance                  0.1.3                    pypi_0    pypi
dlinfo                    1.2.1                    pypi_0    pypi
dnspython                 2.3.0                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
edit-distance             1.0.6                    pypi_0    pypi
editdistance              0.6.2                    pypi_0    pypi
einops                    0.7.0                    pypi_0    pypi
espnet-tts-frontend       0.0.3                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
eventlet                  0.34.3                   pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
fastapi                   0.109.0                  pypi_0    pypi
fastjsonschema            2.19.1                   pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
ffmpy                     0.3.1                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flask                     2.2.5                    pypi_0    pypi
flask-cors                4.0.0                    pypi_0    pypi
flask-restful             0.3.10                   pypi_0    pypi
flask-socketio            5.3.6                    pypi_0    pypi
flask-talisman            1.1.0                    pypi_0    pypi
fonttools                 4.47.2                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2023.10.0                pypi_0    pypi
fugashi                   1.3.0                    pypi_0    pypi
funasr                    0.8.8                    pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
g2p                       1.1.20230822             pypi_0    pypi
g2p-en                    2.1.0                    pypi_0    pypi
gast                      0.5.4                    pypi_0    pypi
google-auth               2.26.2                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
gputil                    1.4.0                    pypi_0    pypi
gradio                    3.50.2                   pypi_0    pypi
gradio-client             0.6.1                    pypi_0    pypi
greenlet                  3.0.3                    pypi_0    pypi
grpcio                    1.60.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
h5py                      3.10.0                   pypi_0    pypi
hdbscan                   0.8.33                   pypi_0    pypi
htmlmin                   0.1.12                   pypi_0    pypi
httpcore                  1.0.2                    pypi_0    pypi
httpx                     0.26.0                   pypi_0    pypi
huggingface-hub           0.20.2                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
idna                      3.6                      pypi_0    pypi
imagehash                 4.3.1                    pypi_0    pypi
importlib-metadata        7.0.1                    pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
inflect                   7.0.0                    pypi_0    pypi
ipykernel                 6.29.0                   pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
ipywidgets                8.1.1                    pypi_0    pypi
isodate                   0.6.1                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jaconv                    0.3.4                    pypi_0    pypi
jamo                      0.4.1                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
json5                     0.9.14                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.21.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.6.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.7.1                    pypi_0    pypi
jupyter-events            0.9.0                    pypi_0    pypi
jupyter-lsp               2.2.2                    pypi_0    pypi
jupyter-server            2.12.5                   pypi_0    pypi
jupyter-server-terminals  0.5.1                    pypi_0    pypi
jupyterlab                4.0.10                   pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.25.2                   pypi_0    pypi
jupyterlab-widgets        3.0.9                    pypi_0    pypi
kaldiio                   2.18.0                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
langid                    1.1.6                    pypi_0    pypi
language-tags             1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h7f98852_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 13.2.0               h807b86a_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgomp                   13.2.0               h807b86a_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libnsl                    2.0.1                hd590300_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
librosa                   0.9.2                    pypi_0    pypi
libsqlite                 3.44.2               h2797004_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libuuid                   2.38.1               h0b41bf4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxcrypt                 4.4.36               hd590300_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.2.13               hd590300_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
llvmlite                  0.41.1                   pypi_0    pypi
loguru                    0.7.2                    pypi_0    pypi
lxml                      5.1.0                    pypi_0    pypi
markdown                  3.5.2                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.4                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mecab-python3             1.0.8                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
modelscope                1.7.1                    pypi_0    pypi
more-itertools            10.2.0                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multimethod               1.10                     pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
munkres                   1.1.4                    pypi_0    pypi
nbclient                  0.9.0                    pypi_0    pypi
nbconvert                 7.14.2                   pypi_0    pypi
nbformat                  5.9.2                    pypi_0    pypi
ncurses                   6.4                  h59595ed_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nest-asyncio              1.5.9                    pypi_0    pypi
networkx                  2.8.4                    pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
notebook                  7.0.6                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
num2words                 0.5.13                   pypi_0    pypi
numba                     0.58.1                   pypi_0    pypi
numpy                     1.22.0                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.18.1                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.3.101                 pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
openai-whisper            20231117                 pypi_0    pypi
openi                     1.2.2                    pypi_0    pypi
openpyxl                  3.1.2                    pypi_0    pypi
openssl                   3.2.0                hd590300_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
orjson                    3.9.10                   pypi_0    pypi
oss2                      2.18.4                   pypi_0    pypi
overrides                 7.4.0                    pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pandas-profiling          3.6.6                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
panphon                   0.20.0                   pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
phik                      0.12.4                   pypi_0    pypi
phonemizer                3.2.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.2             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              4.1.0                    pypi_0    pypi
pooch                     1.8.0                    pypi_0    pypi
proces                    0.1.7                    pypi_0    pypi
prometheus-client         0.19.0                   pypi_0    pypi
prompt-toolkit            3.0.43                   pypi_0    pypi
protobuf                  4.25.2                   pypi_0    pypi
psutil                    5.9.7                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyarrow                   14.0.2                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydantic                  2.5.3                    pypi_0    pypi
pydantic-core             2.14.6                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pykakasi                  2.2.1                    pypi_0    pypi
pylatexenc                2.10                     pypi_0    pypi
pyopenjtalk-prebuilt      0.3.0                    pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pypinyin                  0.50.0                   pypi_0    pypi
python                    3.8.18          hd12c33a_1_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-engineio           4.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
python-socketio           5.11.0                   pypi_0    pypi
pytorch-wpe               0.0.1                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.2                   pypi_0    pypi
qtconsole                 5.5.1                    pypi_0    pypi
qtpy                      2.4.1                    pypi_0    pypi
rdflib                    7.0.0                    pypi_0    pypi
readline                  8.2                  h8228510_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
referencing               0.32.1                   pypi_0    pypi
regex                     2023.12.25               pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
resampy                   0.4.2                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986                   1.5.0                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rotary-embedding-torch    0.5.3                    pypi_0    pypi
rpds-py                   0.17.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.4.1                    pypi_0    pypi
scikit-learn              1.1.3                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.12.2                   pypi_0    pypi
segments                  2.2.1                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                69.0.3             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
simple-websocket          1.0.0                    pypi_0    pypi
simplejson                3.19.2                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
starlette                 0.35.1                   pypi_0    pypi
statsmodels               0.14.1                   pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tangled-up-in-unicode     0.2.0                    pypi_0    pypi
tensorboard               2.14.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
terminado                 0.18.0                   pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
textgrid                  1.5                      pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tiktoken                  0.5.2                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tokenizers                0.15.0                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.1.1+cu118              pypi_0    pypi
torch-complex             0.4.3                    pypi_0    pypi
torchaudio                2.1.1+cu118              pypi_0    pypi
torchvision               0.16.1+cu118             pypi_0    pypi
tornado                   6.4                      pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.14.1                   pypi_0    pypi
transformers              4.36.2                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
typeguard                 4.1.5                    pypi_0    pypi
types-python-dateutil     2.8.19.20240106          pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2023.4                   pypi_0    pypi
umap                      0.1.1                    pypi_0    pypi
unicodecsv                0.14.1                   pypi_0    pypi
unidecode                 1.3.8                    pypi_0    pypi
unidic-lite               1.0.8                    pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
uritemplate               4.1.1                    pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
uvicorn                   0.26.0                   pypi_0    pypi
vector-quantize-pytorch   1.12.11                  pypi_0    pypi
visions                   0.7.5                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.7.0                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.42.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
widgetsnbextension        4.0.9                    pypi_0    pypi
wordcloud                 1.9.3                    pypi_0    pypi
wrapt                     1.16.0                   pypi_0    pypi
wsproto                   1.2.0                    pypi_0    pypi
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yapf                      0.40.2                   pypi_0    pypi
yarl                      1.9.4                    pypi_0    pypi
ydata-profiling           4.6.4                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
```

**Reply by windforestfiremountain** [reply]
然后如果直接用`CUDA_VISIBLE_DEVICES=1 python train_ms.py`训练会报错:
`The client socket has failed to connect to [localhost]:10086 (errno: 99 - Cannot assign requested address)`

**Comment by andymethane** [comment]
您好，我遇到了相同问题，请问你解决了吗？

**Comment by yuGAN6** [comment]
@windforestfiremountain @andymethane 
我也遇到了同样问题，最后发现是由生成隐变量 z 预测的音频 y_hat 的 ids_slice，切片范围超出真实音频 y 的长度了，所以报错下标越界。在切片函数里面对 y 做一下 padding 就好了。

项目代码用的切片方法slice_segments和原始VITS的有差别，所以不能正常地在python中报错，而是报了底层c++的错误。改成下面的函数即可正常运行。

commons.py - slice_segments
```python
def slice_segments(x, ids_str, segment_size=4):
  ret = torch.zeros_like(x[:, :, :segment_size])
  for i in range(x.size(0)):
    idx_str = ids_str[i]
    idx_end = idx_str + segment_size
    if idx_end > x.size(-1):
        # pad x
        x = F.pad(x, (0, (idx_end - x.size(-1)), 0, 0), "constant", 0)
    try:
        ret[i] = x[i, :, idx_str:idx_end]
    except Exception as e:
        print(i, x.shape, idx_str, idx_end)
        raise e
  return ret
```

**Comment by GDbbq** [comment]
检查下n_speakers是否正确
